/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (LDAPUserInformation.as).
 */

package com.eim.utility.ldap.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class LDAPUserInformationBase implements IExternalizable {

        public var _account:String;
        public var _active:Boolean;
        public var _adName:String;
        public var _authorized:Boolean;
        public var _displayName:String;
        public var _emailAddress:String;
        public var _exists:Boolean;
        public var _firstName:String;
        public var _groups:ListCollectionView;
        public var _homeDirectory:String;
        public var _key:String;
        public var _lastName:String;
        public var _locked:int;

        public function set account(value:String):void {
            _account = value;
        }
        public function get account():String {
            return _account;
        }

        public function set active(value:Boolean):void {
            _active = value;
        }
        public function get active():Boolean {
            return _active;
        }

        public function set adName(value:String):void {
            _adName = value;
        }
        public function get adName():String {
            return _adName;
        }

        public function set authorized(value:Boolean):void {
            _authorized = value;
        }
        public function get authorized():Boolean {
            return _authorized;
        }

        public function set displayName(value:String):void {
            _displayName = value;
        }
        public function get displayName():String {
            return _displayName;
        }

        public function set emailAddress(value:String):void {
            _emailAddress = value;
        }
        public function get emailAddress():String {
            return _emailAddress;
        }

        public function set exists(value:Boolean):void {
            _exists = value;
        }
        public function get exists():Boolean {
            return _exists;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set groups(value:ListCollectionView):void {
            _groups = value;
        }
        public function get groups():ListCollectionView {
            return _groups;
        }

        public function set homeDirectory(value:String):void {
            _homeDirectory = value;
        }
        public function get homeDirectory():String {
            return _homeDirectory;
        }

        public function set key(value:String):void {
            _key = value;
        }
        public function get key():String {
            return _key;
        }

        public function set lastName(value:String):void {
            _lastName = value;
        }
        public function get lastName():String {
            return _lastName;
        }

        public function set locked(value:int):void {
            _locked = value;
        }
        public function get locked():int {
            return _locked;
        }

        public function readExternal(input:IDataInput):void {
            _account = input.readObject() as String;
            _active = input.readObject() as Boolean;
            _adName = input.readObject() as String;
            _authorized = input.readObject() as Boolean;
            _displayName = input.readObject() as String;
            _emailAddress = input.readObject() as String;
            _exists = input.readObject() as Boolean;
            _firstName = input.readObject() as String;
            _groups = input.readObject() as ListCollectionView;
            _homeDirectory = input.readObject() as String;
            _key = input.readObject() as String;
            _lastName = input.readObject() as String;
            _locked = input.readObject() as int;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_account);
            output.writeObject(_active);
            output.writeObject(_adName);
            output.writeObject(_authorized);
            output.writeObject(_displayName);
            output.writeObject(_emailAddress);
            output.writeObject(_exists);
            output.writeObject(_firstName);
            output.writeObject(_groups);
            output.writeObject(_homeDirectory);
            output.writeObject(_key);
            output.writeObject(_lastName);
            output.writeObject(_locked);
        }
    }
}