/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eim.utility.ldap.model {

    [Bindable]
    [RemoteClass(alias="com.eim.utility.ldap.model.LDAPUserInformation")]
    public class LDAPUserInformation extends LDAPUserInformationBase {
    }
}